# Generated by Django 4.1 on 2023-07-14 07:16

from django.db import migrations, models
import django.db.models.deletion
import invoices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True, validators=[invoices.models.validate_date])),
            ],
            options={
                'db_table': 'invoices_invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(choices=[('kg', 'Killo Gram'), ('g', 'Gram')], max_length=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='invoices.invoice')),
            ],
            options={
                'db_table': 'invoices_invoice_detail',
            },
        ),
    ]
